### PR TITLE
Multi-threaded decoding via kaldi support

### PR DESCRIPTION
**Pull request by akashmjn**
Further to discussion on #31, just including the smallest change that would make this viable. Should be quite important to have while working with any reasonable-size dataset. 

Right now `num_threads` is a hardcoded variable in `decode_dnn.sh`

### CODE REVIEW

**Comment by mravanelli** [comment]
OK Merged it. I actually tried with a different number of threads, but the number of jobs I see during decoding is still equal to the number of test chunks. Do you see the same problem?

**Comment by akashmjn** [comment]
It seems to work for me. The correlation is visible with the CPU cores utilisation on htop in my case, so I know it's working. 
A single job per chunk is run with the `latgen-faster-mapped-parallel` binary instead of `latgen-faster-mapped` which itself has subthreads so you'll need to specifically look to view those. 
screen shot 2019-01-23 at 7 53 40 pm

**Comment by mravanelli** [comment]
Ok, great!

thank you!

**Comment by TParcollet** [comment]
It's all about threads and not core. Nonetheless, I have two questions regarding this parallel decoding. 1) Does it harms the final decoding score ? (Should be tested with a full TIMIT recipe). 2) Does it really decrease the decoding time ? (Any measure ?)

**Comment by mravanelli** [comment]
In my simple TIMIT experiment, the performance remains exactly the same,
but the decoding time is similar. Do you guys have a different experience
with that?

Mirco

**Comment by akashmjn** [comment]
From my understanding, it'd be quite unlikely that this affects performance, and you should observe a significant speedup depending on the machine and reasonable size test. 
Looking through [source](http://kaldi-asr.org/doc/latgen-faster-mapped-parallel_8cc.html) it seems like identical utterance-level tasks for decoding are scheduled across multiple thread workers instead of running sequentially.  
I've also seen a similar use in nnet3 recipes for AMI and WSJ, so probably pretty standard? 

I haven't really recorded exact decoding times for my experiments with AMI however it is considerably faster when i'm using upto 10-12 threads on a 12 core machine.

**Comment by mravanelli** [comment]
Perfect,
people can use it now!

**Pull request merged**
