### PR TITLE
[MRG] Clean up source code formatting

### PR DESCRIPTION
**Pull request by shuttle1987**
There's a variety of inconsistent formatting in the source for this project, I've updated some old Python 2 files to be Python 2/3 compatible and run the Python files through the Black code formatting tool. Hopefully no logic is changed here.

### CODE REVIEW

**Comment by csukuangfj** [comment]
The original code is badly formatted, lack of documentation, hard to read and maintain.

**Comment by TParcollet** [comment]
PyTorch-Kaldi was intended as a functional prototype for SpeechBrain. Hence, the code does not rely one any coding guidelines, and we haven't made any video / tutorial / documentation. If you care about a clean code. Then, just wait a few months and SpeecBrain will come. That was not the purpose of PyTorch-Kaldi.

**Comment by shuttle1987** [comment]
Having worked on a speech to text project myself (https://github.com/persephone-tools/persephone) I understand the value of prototypes. I think in this case the changes here will help the project as they are not designed to change any functionality but just to clean up the source code. This will make it much easier for people to read the code and learn from it. If it is possible to verify that this PR has not caused the code to break in any ways it will be a pareto efficient improvement.

**Comment by mravanelli** [comment]
Sure, thank you very much for your help! We will review it right after the upcoming ICASSP 2020 deadline (that is totally eating my time....)

**Comment by mravanelli** [comment]
I checked it and it works! Thank you!

**Pull request merged**
