### PR TITLE
[check_res_dec] Fixing compile WER script

### PR DESCRIPTION
**Pull request by akashmjn**
Existing one didn't seem to work for me. This script also extends functionality with ability to pass multiple exp directories for which best WER are compiled. 
e.g. `./check_res_dec.sh exp/AMI_LSTM_v1 exp/AMI_liGRU_v1` or `./check_res_dec.sh exp/AMI_LSTM*`

### CODE REVIEW

**Comment by mravanelli** [comment]
The way the current script should be called is the following (see run_exp.py):
./check_res_dec.sh exp/TIMIT_MLP_basic/decode_TIMIT_test_out_dnn1/

Does it work with if you call it in this way?

**Comment by akashmjn** [comment]
Good point. Didn't realize I'd break that script. 
I was finding this useful for additionally being able to check results across experiments i.e. `exp/LSTM`, `exp/liGRU` as well as different decode sets such as `exp/tests_v1/LSTM_v1/decode_eval`, `exp/tests_v1/LSTM_v1/decode_dev` 

Making a change that should support both use cases: search for a decode_* folder and then print best WER across scores for each.

**Comment by mravanelli** [comment]
Hi Akash,
maybe what you are looking for is already implemented in RESULT. if you
type "./RESULT" you should be able to see all the results saved in the exp
folder

**Comment by akashmjn** [comment]
Oh gosh, my bad - it's been a while! I remember now. 
There are two parts to this: 

1. The core logic used in both scripts `grep Sum $x/score_*/*.sys 2>/dev/null | ./best_wer.sh` didn't work in my case when working with kaldi's AMI dataset recipe and `score_asclite.sh` for scoring. 
Likely because decoding results are produced with the following structure: `decode_dir/ascore_[VALUE]/*.sys` so a tiny fix with `$dir/*score_*/*.sys` makes it more robust.  

2. I meant to propose change to RESULTS as like with tensorboard sometimes it's better to organize runs with subdirectories and so forth. 

Depending on whether you think these are relevant, I can commit edits accordingly, or leave it out if you think it's too specific.

**Comment by mravanelli** [comment]
Maybe we can simply modify the RESULT script in this way:
- if no argument are specified shows all the results in exp folder
-otherwise show the results in the specified sub-folder...

**Comment by mravanelli** [comment]
I tested it and it works. I merged it. Thank you!

**Pull request merged**
